########################
# SNAKEMAKE PARAMETERS #
########################

# (1) Directories for individual stages of the workflow
input_dir:            input/refseq-genes
intermediate_dir:     /n/scratch/users/a/ak586/refseq-intermediate-800dist-25minsamp
output_dir:           /n/scratch/users/a/ak586/refseq-output-800dist-25minsamp
conda_dir:            .conda

# (2) Parameters for Snakemake execution
use_conda:            True # build conda environments automatically by Snakemake

##############
# PARAMETERS #
##############

# (1) General parameters; notes:
#     - kmer length is
#     - gap distance is
#     - batch size is
#     - cluster sample size is
kmer_length:            26
gap_distance:           4
cluster_sample_size:    4
batch_size:             500
  

# (2) DBSCAN parameters; 
max_distance:           800
min_samples:            25
remove_outliers:        True
