########################
# SNAKEMAKE PARAMETERS #
########################

# (1) Directories for individual stages of the workflow
input_dir:            input/subset
intermediate_dir:     /n/data1/hms/dbmi/baym/arya/data/subset-intermediate-800dist-25minsamp-k20-g4
output_dir:           /n/data1/hms/dbmi/baym/arya/data/subset-output-800dist-25minsamp-k20-g4
conda_dir:            .conda

# (2) Parameters for Snakemake execution
use_conda:            True # build conda environments automatically by Snakemake

##############
# PARAMETERS #
##############

# (1) General parameters; notes:
#     - kmer length is
#     - gap distance is
#     - batch size is
#     - cluster sample size is
kmer_length:            20
gap_distance:           4
cluster_sample_size:    4
batch_size:             500
  

# (2) DBSCAN parameters; 
max_distance:           800
min_samples:            25
remove_outliers:        True
