default-resources:
  - slurm_account=baym
  - slurm_partition=short
  - runtime="5h"
  - mem="4G"


jobs: 500
restart-times: 3
max-jobs-per-second: 100
cores: 14
  
rerun-incomplete: True
printshellcmds: True

groups:
  - prefixsuffix_kmergen=kmergengroup
  - fastmap=fastmapgroup
  - fastmap_process=fastmapprocessgroup  
  - fastmap_distances=fastmapdistances-group
  - parse_distances=fastmapparsedistances-group

group-components:
  - kmergengroup=100
  - fastmapgroup=500
  - fastmapprocessgroup=400
  - fastmapdistances-group=50
  - fastmapparsedistances-group=200
