########################
# SNAKEMAKE PARAMETERS #
########################

# (1) Directories for individual stages of the workflow
input_dir:            input
intermediate_dir:     intermediate
output_dir:           output
conda_dir:            .conda

# (2) Parameters for Snakemake execution
use_conda:            True # build conda environments automatically by Snakemake

##############
# PARAMETERS #
##############

# (1) General parameters; notes:
#     - kmer length defines k for dBGs 
#     - if trees_required is true, then the workflow will insist on user-provided trees
#     - max_colors is the number of hexadecimal color codes to include in the dbg
kmer_length:           31
gap_distance:           4
  

# (2) Mashtree parameters; notes:
#     - sketch size should be at least 10k to achieve a sufficient resolution
mashtree_threads:     8
mashtree_kmer_length: 21
mashtree_sketch_size: 10000
