########################
# SNAKEMAKE PARAMETERS #
########################

# (1) Directories for individual stages of the workflow
input_dir:            input
intermediate_dir:     /n/scratch/users/a/ak586/refseqpost-intermediate-800dist-25minsamp
output_dir:           /n/scratch/users/a/ak586/refseqpost-output-800dist-25minsamp
previnput_dir:        ../input/refseq-genes
previntermediate_dir:     /n/scratch/users/a/ak586/refseq-intermediate-800dist-25minsamp
prevoutput_dir:           /n/scratch/users/a/ak586/refseq-output-800dist-25minsamp
conda_dir:            .conda

# (2) Parameters for Snakemake execution
use_conda:            True # build conda environments automatically by Snakemake

bakta_db:             /n/data1/hms/dbmi/baym/databases/bakta_dbv5/db

##############
# PARAMETERS #
##############

# (1) General parameters; notes:
number_genomes:               500
window_size:                  500
kmer_length:                  26

number_annotate:              4
number_matching_decompress:   0
