########################
# SNAKEMAKE PARAMETERS #
########################

# (1) Directories for individual stages of the workflow
input_dir:            input
intermediate_dir:     /home/ak586/baym/projects/prefixsuffix-kmer/manual/sensitivity_analysis/fiverandos/intermediate
output_dir:           /home/ak586/baym/projects/prefixsuffix-kmer/manual/sensitivity_analysis/fiverandos/output
previnput_dir:        /n/data1/hms/dbmi/baym/arya/projects/prefixsuffix-kmer/manual/sensitivity_analysis/fiverandos
previntermediate_dir:     /n/scratch/users/a/ak586/refseq-intermediate-800dist-25minsamp
prevoutput_dir:           /n/data1/hms/dbmi/baym/arya/data/subset-subset-output-800dist-25minsamp-k26-g4
conda_dir:            .conda

# (2) Parameters for Snakemake execution
use_conda:            True # build conda environments automatically by Snakemake

bakta_db:             /n/data1/hms/dbmi/baym/databases/bakta_dbv6/db

##############
# PARAMETERS #
##############

# (1) General parameters; notes:
number_genomes:               500
window_size:                  500
kmer_length:                  26

number_annotate:              3
number_matching_decompress:   10000
