########################
# SNAKEMAKE PARAMETERS #
########################

# (1) Directories for individual stages of the workflow

previnput_dir:        /n/data1/hms/dbmi/baym/arya/projects/prefixsuffix-kmer/input 
previntermediate_dir:     /n/scratch/users/a/ak586/prefixsuffix-intermediate 
prevoutput_dir:           /n/scratch/users/a/ak586/prefixsuffix-output-3

intermediate_dir:     /n/scratch/users/a/ak586/prefixsuffix-post-intermediate-3
output_dir:           /n/scratch/users/a/ak586/prefixsuffix-post-output-3

fastmap_indices: /home/ak586/baym/projects/prefixsuffix-kmer/intermediate/bwa_indices/allthebacteriav2

# (2) Parameters for Snakemake execution
use_conda:            True # build conda environments automatically by Snakemake
conda_dir:            .conda

##############
# PARAMETERS #
##############

kmer_length:                  27
num_filter_genomes:           10
threshold:                    2.0

number_genomes:               300
window_size:                  200
flankkb_decompress:           5

number_annotate:              3
number_matching_decompress:   10000

internal_pad:                 100
