########################
# SNAKEMAKE PARAMETERS #
########################

# (1) Directories for individual stages of the workflow
previnput_dir:        ../../.test/input
intermediate_dir:     intermediate
previntermediate_dir: ../../.test/intermediate
output_dir:           output
prevoutput_dir:       ../../.test/output
conda_dir:            .conda

# (2) Parameters for Snakemake execution
use_conda:            True # build conda environments automatically by Snakemake

bakta_db:             /n/data1/hms/dbmi/baym/databases/bakta_dbv5/db

##############
# PARAMETERS #
##############

